baseurl = "http://victormendonca.com"
# baseurl = "/"
languageCode = "en-us"
title = "Victor Mendon√ßa"
theme = "hugo-base-theme-custom"
[params]
  description = ""
  mainIcon = "/img/hugo.png"

# [[params.social]]
#     title = "Personal"
#     url = "https://victorbrca.github.io/personal"
[[params.social]]
    title = "Professional"
    url = "http://geekit.ca/"
[[params.social]]
    title = "Blog"
    url = "http://blog.victormendonca.com"
